Add files via upload

diff --git a/ivdeb b/ivdeb
--- a/ivdeb
+++ b/ivdeb
@@ -14,6 +14,14 @@ then
   exit 1
 fi 
 
+# Verificando se o arquivo existe ou não
+ls -lA $1 >> /dev/null
+if [ $? != 0 ]
+then
+  echo "No such file directory."
+  exit 1
+fi
+
 # Criando diretorio temporario
 echo "Making directory temp..."
 mkdir temp
@@ -24,24 +32,26 @@ cd temp
 
 #Descompctando deb.
 echo "Unpacking deb file"
-out_deb=`ar x $1`
-if [ $? != 0 ]
-then
-  echo "An error has occured, the file $1 may be corrupt."
-  mv $1 .. > /dev/null
-  cd ..
-  sudo rm -rf temp/
-  exit 1
-fi
+ar x $1
+
+
+#if [ $? != 0 ]
+#then
+#  echo "An error has occured, the file $1 may be corrupt."
+#  mv $1 .. > /dev/null
+#  cd ..
+#  sudo rm -rf temp/
+ # exit 1
+#fi
 
 mv $1 .. #Movendo deb original para fora da pasta temp.
 
 echo "Unpacking control.tar.xz"
-tar -xvf control.tar.*
+tar -xvf control.tar.* >> ../log_file.log
 if [ $? != 0 ]
 then
   echo "An error has occured, the file $1 may be corrupt."
-  mv $1 .. > /dev/null
+  mv $1 ..
   cd ..
   sudo rm -rf temp/
   exit 1
@@ -52,11 +62,11 @@ name_package=`cat control | grep Package | cut -d " " -f 2`
 requires_package=`cat control | grep Depends | cut -d " " -f 2`
 
 echo "Unpacking data.tar.xz"
-tar xvf data.tar.*
+tar xvf data.tar.* >> ../log_file.log
 if [ $? != 0 ]
 then
   echo "An error has occured, the file $1 may be corrupt."
-  mv $1 .. > /dev/null
+  mv $1 ..
   cd ..
   sudo rm -rf temp/
   exit 1
